<?php

namespace Tests\Traits;

trait CreatesNamiMember {
    public function createNamiMember($overrides = []) {
        return (object) array_merge([
            'jungpfadfinder' => null,
            'mglType' => 'Mitglied',
            'geschlecht' => 'männlich',
            'staatsangehoerigkeit' => 'deutsch',
            'ersteTaetigkeitId' => null,
            'ersteUntergliederung' => 'Jungpfadfinder',
            'emailVertretungsberechtigter' => 'eltern@test.de',
            'lastUpdated' => '2016-01-20 19:45:24',
            'ersteTaetigkeit' => null,
            'nameZusatz' => 'Zusatz',
            'id' => 5678,
            'staatsangehoerigkeitId' => 1054,
            'version' => 30,
            'sonst01' => false,
            'sonst02' => false,
            'spitzname' => 'Spitz',
            'landId' => 1,
            'staatsangehoerigkeitText' => 'Andere',
            'gruppierungId' => 100105,
            'mglTypeId' => 'MITGLIED',
            'beitragsart' => 'Voller Beitrag',
            'nachname' => 'Mustermann',
            'eintrittsdatum' =>'2015-05-27 00:00:00',
            'rover' => null,
            'region' => 'Nordrhein-Westfalen (Deutschland)',
            'status' => 'Aktiv',
            'konfession' => 'evangelisch / protestantisch',
            'fixBeitrag' => null,
            'konfessionId' => 2,
            'zeitschriftenversand' => true,
            'pfadfinder' => null,
            'telefon3' => '+49 222 33333',
            'kontoverbindung' => (object)[
                'id' => 227580,
                'institut' => '',
                'bankleitzahl' => '',
                'kontonummer' => '',
                'iban' => '',
                'bic' => '',
                'kontoinhaber' => '',
                'mitgliedsNummer' => 245852,
                'zahlungsKonditionId' => null,
                'zahlungsKondition' => null
            ],
            "geschlechtId" => 19,
            'land' => 'Deutschland',
            'email' => 'member@test.de',
            'telefon1' => '+49 212 319345',
            'woelfling' => null,
            'telefon2' => '+49 163 1725774',
            'strasse' => 'Strasse 1',
            'vorname' => 'Max',
            'mitgliedsNummer' => 245852,
            'gruppierung' => 'Solingen-Wald, Silva 100105',
            'austrittsDatum' => '',
            'ort' => 'City',
            'ersteUntergliederungId' => null,
            'wiederverwendenFlag' => true,
            'regionId' => 10,
            'geburtsDatum' => '2005-12-28 00:00:00',
            'stufe' => 'Jungpfadfinder',
            'genericField1' => '',
            'genericField2' => '',
            'telefax' => '+49 212 4455555',
            'beitragsartId' => 1,
            'plz' => '42777'
        ], $overrides);
    }
}
