<?php

use Illuminate\Database\Seeder;
use App\Nationality;

class NationalitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
		Nationality::create(['title' => 'Bosnisch', 'nami_id' => 1284, 'nami_title' => 'Bosnisch']);
		Nationality::create(['title' => 'USA/SLO', 'nami_id' => 1286, 'nami_title' => 'USA/SLO']);
		Nationality::create(['title' => 'serb.montenegro', 'nami_id' => 1287, 'nami_title' => 'serb.montenegro']);
		Nationality::create(['title' => 'serbisch', 'nami_id' => 1288, 'nami_title' => 'serbisch']);
		Nationality::create(['title' => 'französich', 'nami_id' => 1289, 'nami_title' => 'französich']);
		Nationality::create(['title' => 'A', 'nami_id' => 1291, 'nami_title' => 'A']);
		Nationality::create(['title' => 'holländisch', 'nami_id' => 1292, 'nami_title' => 'holländisch']);
		Nationality::create(['title' => 'Kenia', 'nami_id' => 1293, 'nami_title' => 'Kenia']);
		Nationality::create(['title' => 'madegaschi', 'nami_id' => 1294, 'nami_title' => 'madegaschi']);
		Nationality::create(['title' => '+ amerikanisch', 'nami_id' => 1295, 'nami_title' => '+ amerikanisch']);
		Nationality::create(['title' => 'St. Lucianer', 'nami_id' => 1296, 'nami_title' => 'St. Lucianer']);
		Nationality::create(['title' => 'lettisch', 'nami_id' => 1297, 'nami_title' => 'lettisch']);
		Nationality::create(['title' => 'Iran', 'nami_id' => 1298, 'nami_title' => 'Iran']);
		Nationality::create(['title' => 'japanisch', 'nami_id' => 1299, 'nami_title' => 'japanisch']);
		Nationality::create(['title' => 'österr. + südafr.', 'nami_id' => 1304, 'nami_title' => 'österr. + südafr.']);
		Nationality::create(['title' => 'italiano', 'nami_id' => 1306, 'nami_title' => 'italiano']);
		Nationality::create(['title' => 'Ukrainerin', 'nami_id' => 1308, 'nami_title' => 'Ukrainerin']);
		Nationality::create(['title' => 'deutsch', 'nami_id' => 1054, 'nami_title' => 'deutsch']);
		Nationality::create(['title' => 'Serbien-Montenegro', 'nami_id' => 1310, 'nami_title' => 'Serbien-Montenegro']);
		Nationality::create(['title' => 'Jugoslawisch/Kosovo', 'nami_id' => 1311, 'nami_title' => 'Jugoslawisch/Kosovo']);
		Nationality::create(['title' => '', 'nami_id' => 1056, 'nami_title' => '']);
		Nationality::create(['title' => 'ungarisch', 'nami_id' => 1312, 'nami_title' => 'ungarisch']);
		Nationality::create(['title' => 'andere', 'nami_id' => 1057, 'nami_title' => 'andere']);
		Nationality::create(['title' => 'chinesisch', 'nami_id' => 1058, 'nami_title' => 'chinesisch']);
		Nationality::create(['title' => 'österreichisch', 'nami_id' => 1059, 'nami_title' => 'österreichisch']);
		Nationality::create(['title' => 'Thailand', 'nami_id' => 1315, 'nami_title' => 'Thailand']);
		Nationality::create(['title' => 'italienisch', 'nami_id' => 1060, 'nami_title' => 'italienisch']);
		Nationality::create(['title' => 'EU', 'nami_id' => 1061, 'nami_title' => 'EU']);
		Nationality::create(['title' => 'maltesisch', 'nami_id' => 1317, 'nami_title' => 'maltesisch']);
		Nationality::create(['title' => 'Portugiesisch', 'nami_id' => 1318, 'nami_title' => 'Portugiesisch']);
		Nationality::create(['title' => 'niederländisch', 'nami_id' => 1064, 'nami_title' => 'niederländisch']);
		Nationality::create(['title' => 'schweizerisch', 'nami_id' => 1320, 'nami_title' => 'schweizerisch']);
		Nationality::create(['title' => 'kenianisch', 'nami_id' => 1065, 'nami_title' => 'kenianisch']);
		Nationality::create(['title' => 'Tschechische Republick', 'nami_id' => 1321, 'nami_title' => 'Tschechische Republick']);
		Nationality::create(['title' => 'kroatisch', 'nami_id' => 1066, 'nami_title' => 'kroatisch']);
		Nationality::create(['title' => 'brasilianisch', 'nami_id' => 1067, 'nami_title' => 'brasilianisch']);
		Nationality::create(['title' => 'weißrussisch', 'nami_id' => 1323, 'nami_title' => 'weißrussisch']);
		Nationality::create(['title' => 'polnisch', 'nami_id' => 1069, 'nami_title' => 'polnisch']);
		Nationality::create(['title' => 'Bolivien', 'nami_id' => 1326, 'nami_title' => 'Bolivien']);
		Nationality::create(['title' => 'türkisch', 'nami_id' => 1071, 'nami_title' => 'türkisch']);
		Nationality::create(['title' => 'österr.', 'nami_id' => 1327, 'nami_title' => 'österr.']);
		Nationality::create(['title' => 'Grieche', 'nami_id' => 1329, 'nami_title' => 'Grieche']);
		Nationality::create(['title' => 'portugiesisch', 'nami_id' => 1074, 'nami_title' => 'portugiesisch']);
		Nationality::create(['title' => 'Burundi', 'nami_id' => 1331, 'nami_title' => 'Burundi']);
		Nationality::create(['title' => 'amerikanisch', 'nami_id' => 1076, 'nami_title' => 'amerikanisch']);
		Nationality::create(['title' => 'Brittisch', 'nami_id' => 1333, 'nami_title' => 'Brittisch']);
		Nationality::create(['title' => 'österreich', 'nami_id' => 1081, 'nami_title' => 'österreich']);
		Nationality::create(['title' => 'Albanien', 'nami_id' => 1338, 'nami_title' => 'Albanien']);
		Nationality::create(['title' => 'Nigeria', 'nami_id' => 1339, 'nami_title' => 'Nigeria']);
		Nationality::create(['title' => 'GB', 'nami_id' => 1340, 'nami_title' => 'GB']);
		Nationality::create(['title' => 'mazedonisch', 'nami_id' => 1341, 'nami_title' => 'mazedonisch']);
		Nationality::create(['title' => 'britisch', 'nami_id' => 1086, 'nami_title' => 'britisch']);
		Nationality::create(['title' => 'Togolaise', 'nami_id' => 1343, 'nami_title' => 'Togolaise']);
		Nationality::create(['title' => 'Schweizer', 'nami_id' => 1088, 'nami_title' => 'Schweizer']);
		Nationality::create(['title' => 'pakistanisch', 'nami_id' => 1344, 'nami_title' => 'pakistanisch']);
		Nationality::create(['title' => 'Thai', 'nami_id' => 1089, 'nami_title' => 'Thai']);
		Nationality::create(['title' => 'österreichschich/norwegisch', 'nami_id' => 1345, 'nami_title' => 'österreichschich/norwegisch']);
		Nationality::create(['title' => 'litauisch', 'nami_id' => 1091, 'nami_title' => 'litauisch']);
		Nationality::create(['title' => 'Portugal', 'nami_id' => 1347, 'nami_title' => 'Portugal']);
		Nationality::create(['title' => 'griechisch', 'nami_id' => 1092, 'nami_title' => 'griechisch']);
		Nationality::create(['title' => 'Italienisch-Österr.', 'nami_id' => 1348, 'nami_title' => 'Italienisch-Österr.']);
		Nationality::create(['title' => 'schweizerisch ', 'nami_id' => 1093, 'nami_title' => 'schweizerisch ']);
		Nationality::create(['title' => 'guatemaltekisch', 'nami_id' => 1349, 'nami_title' => 'guatemaltekisch']);
		Nationality::create(['title' => 'belgisch', 'nami_id' => 1094, 'nami_title' => 'belgisch']);
		Nationality::create(['title' => 'nicht bekannt', 'nami_id' => 1350, 'nami_title' => 'nicht bekannt']);
		Nationality::create(['title' => 'Portugiesich', 'nami_id' => 1352, 'nami_title' => 'Portugiesich']);
		Nationality::create(['title' => 'lettisch', 'nami_id' => 1102, 'nami_title' => 'lettisch']);
		Nationality::create(['title' => 'französisch', 'nami_id' => 1103, 'nami_title' => 'französisch']);
		Nationality::create(['title' => 'spanisch', 'nami_id' => 1104, 'nami_title' => 'spanisch']);
		Nationality::create(['title' => 'british', 'nami_id' => 1360, 'nami_title' => 'british']);
		Nationality::create(['title' => 'marokkanisch', 'nami_id' => 1361, 'nami_title' => 'marokkanisch']);
		Nationality::create(['title' => 'Togo', 'nami_id' => 1106, 'nami_title' => 'Togo']);
		Nationality::create(['title' => 'albanisch', 'nami_id' => 1107, 'nami_title' => 'albanisch']);
		Nationality::create(['title' => 'Niederländer', 'nami_id' => 1364, 'nami_title' => 'Niederländer']);
		Nationality::create(['title' => 'Sri Lanka', 'nami_id' => 1110, 'nami_title' => 'Sri Lanka']);
		Nationality::create(['title' => 'estnisch', 'nami_id' => 1366, 'nami_title' => 'estnisch']);
		Nationality::create(['title' => 'Indien', 'nami_id' => 1111, 'nami_title' => 'Indien']);
		Nationality::create(['title' => 'Eritrea', 'nami_id' => 1112, 'nami_title' => 'Eritrea']);
		Nationality::create(['title' => 'slowakisch', 'nami_id' => 1370, 'nami_title' => 'slowakisch']);
		Nationality::create(['title' => 'Serbe', 'nami_id' => 1115, 'nami_title' => 'Serbe']);
		Nationality::create(['title' => 'Algerisch', 'nami_id' => 1372, 'nami_title' => 'Algerisch']);
		Nationality::create(['title' => 'indonesisch', 'nami_id' => 1117, 'nami_title' => 'indonesisch']);
		Nationality::create(['title' => 'griech.', 'nami_id' => 1373, 'nami_title' => 'griech.']);
		Nationality::create(['title' => 'yugoslawisch', 'nami_id' => 1118, 'nami_title' => 'yugoslawisch']);
		Nationality::create(['title' => 'englisch/plonisch', 'nami_id' => 1119, 'nami_title' => 'englisch/plonisch']);
		Nationality::create(['title' => 'irisch', 'nami_id' => 1375, 'nami_title' => 'irisch']);
		Nationality::create(['title' => 'bosnisch-herzegow.', 'nami_id' => 1120, 'nami_title' => 'bosnisch-herzegow.']);
		Nationality::create(['title' => 'Jugoslawisch', 'nami_id' => 1376, 'nami_title' => 'Jugoslawisch']);
		Nationality::create(['title' => 'Italienisch', 'nami_id' => 1121, 'nami_title' => 'Italienisch']);
		Nationality::create(['title' => 'Irisch', 'nami_id' => 1122, 'nami_title' => 'Irisch']);
		Nationality::create(['title' => 'libanesisch', 'nami_id' => 1123, 'nami_title' => 'libanesisch']);
		Nationality::create(['title' => 'iranisch', 'nami_id' => 1124, 'nami_title' => 'iranisch']);
		Nationality::create(['title' => 'Bulgarien/Belgien', 'nami_id' => 1380, 'nami_title' => 'Bulgarien/Belgien']);
		Nationality::create(['title' => 'polnisch/italiensch', 'nami_id' => 1381, 'nami_title' => 'polnisch/italiensch']);
		Nationality::create(['title' => 'amerikanisch', 'nami_id' => 1126, 'nami_title' => 'amerikanisch']);
		Nationality::create(['title' => 'salvadorianisch', 'nami_id' => 1127, 'nami_title' => 'salvadorianisch']);
		Nationality::create(['title' => 'Russische Föderation', 'nami_id' => 1384, 'nami_title' => 'Russische Föderation']);
		Nationality::create(['title' => 'US', 'nami_id' => 1129, 'nami_title' => 'US']);
		Nationality::create(['title' => 'Rumänisch', 'nami_id' => 1385, 'nami_title' => 'Rumänisch']);
		Nationality::create(['title' => 'Ungarn', 'nami_id' => 1130, 'nami_title' => 'Ungarn']);
		Nationality::create(['title' => 'U.S. Amerikaner', 'nami_id' => 1386, 'nami_title' => 'U.S. Amerikaner']);
		Nationality::create(['title' => 'SERBIEN', 'nami_id' => 1387, 'nami_title' => 'SERBIEN']);
		Nationality::create(['title' => 'Spanisch', 'nami_id' => 1132, 'nami_title' => 'Spanisch']);
		Nationality::create(['title' => 'ukrainisch', 'nami_id' => 1133, 'nami_title' => 'ukrainisch']);
		Nationality::create(['title' => 'Belgier', 'nami_id' => 1389, 'nami_title' => 'Belgier']);
		Nationality::create(['title' => 'eritreisch', 'nami_id' => 1134, 'nami_title' => 'eritreisch']);
		Nationality::create(['title' => 'philippinisch', 'nami_id' => 1135, 'nami_title' => 'philippinisch']);
		Nationality::create(['title' => 'Ghana', 'nami_id' => 1391, 'nami_title' => 'Ghana']);
		Nationality::create(['title' => 'jugoslawisch', 'nami_id' => 1137, 'nami_title' => 'jugoslawisch']);
		Nationality::create(['title' => 'Amerikaner', 'nami_id' => 1393, 'nami_title' => 'Amerikaner']);
		Nationality::create(['title' => 'tschechisch', 'nami_id' => 1138, 'nami_title' => 'tschechisch']);
		Nationality::create(['title' => 'kongolesisch', 'nami_id' => 1394, 'nami_title' => 'kongolesisch']);
		Nationality::create(['title' => 'portugisiesch', 'nami_id' => 1395, 'nami_title' => 'portugisiesch']);
		Nationality::create(['title' => 'Bosnien und Herzegowina', 'nami_id' => 1140, 'nami_title' => 'Bosnien und Herzegowina']);
		Nationality::create(['title' => 'Portugisiesch', 'nami_id' => 1396, 'nami_title' => 'Portugisiesch']);
		Nationality::create(['title' => 'Türkisch', 'nami_id' => 1141, 'nami_title' => 'Türkisch']);
		Nationality::create(['title' => 'nigerianisch', 'nami_id' => 1397, 'nami_title' => 'nigerianisch']);
		Nationality::create(['title' => 'bosnisch', 'nami_id' => 1142, 'nami_title' => 'bosnisch']);
		Nationality::create(['title' => 'Indonesisch', 'nami_id' => 1398, 'nami_title' => 'Indonesisch']);
		Nationality::create(['title' => 'British', 'nami_id' => 1143, 'nami_title' => 'British']);
		Nationality::create(['title' => 'griechisch-amerikanisch', 'nami_id' => 1399, 'nami_title' => 'griechisch-amerikanisch']);
		Nationality::create(['title' => 'portugisisch', 'nami_id' => 1144, 'nami_title' => 'portugisisch']);
		Nationality::create(['title' => 'CH', 'nami_id' => 1146, 'nami_title' => 'CH']);
		Nationality::create(['title' => 'Malaysian', 'nami_id' => 1405, 'nami_title' => 'Malaysian']);
		Nationality::create(['title' => 'Filipina', 'nami_id' => 1150, 'nami_title' => 'Filipina']);
		Nationality::create(['title' => 'vietnam', 'nami_id' => 1151, 'nami_title' => 'vietnam']);
		Nationality::create(['title' => 'Kroatien', 'nami_id' => 1152, 'nami_title' => 'Kroatien']);
		Nationality::create(['title' => 'venezuelanisch', 'nami_id' => 1408, 'nami_title' => 'venezuelanisch']);
		Nationality::create(['title' => 'Brasilien', 'nami_id' => 1410, 'nami_title' => 'Brasilien']);
		Nationality::create(['title' => 'niederländer', 'nami_id' => 1155, 'nami_title' => 'niederländer']);
		Nationality::create(['title' => 'U.S.Amerikaner', 'nami_id' => 1411, 'nami_title' => 'U.S.Amerikaner']);
		Nationality::create(['title' => 'vietnamesisch', 'nami_id' => 1156, 'nami_title' => 'vietnamesisch']);
		Nationality::create(['title' => 'ECU', 'nami_id' => 1412, 'nami_title' => 'ECU']);
		Nationality::create(['title' => 'Luxemburgisch', 'nami_id' => 1413, 'nami_title' => 'Luxemburgisch']);
		Nationality::create(['title' => 'Britisch', 'nami_id' => 1158, 'nami_title' => 'Britisch']);
		Nationality::create(['title' => 'Österreich', 'nami_id' => 1159, 'nami_title' => 'Österreich']);
		Nationality::create(['title' => 'amerikanisch / polnisch', 'nami_id' => 1415, 'nami_title' => 'amerikanisch / polnisch']);
		Nationality::create(['title' => 'kanadisch', 'nami_id' => 1160, 'nami_title' => 'kanadisch']);
		Nationality::create(['title' => 'schweiz', 'nami_id' => 1416, 'nami_title' => 'schweiz']);
		Nationality::create(['title' => 'Thailänder', 'nami_id' => 1417, 'nami_title' => 'Thailänder']);
		Nationality::create(['title' => 'Irakisch', 'nami_id' => 1162, 'nami_title' => 'Irakisch']);
		Nationality::create(['title' => 'Peru', 'nami_id' => 1418, 'nami_title' => 'Peru']);
		Nationality::create(['title' => 'Italien', 'nami_id' => 1163, 'nami_title' => 'Italien']);
		Nationality::create(['title' => 'Kirgystan', 'nami_id' => 1164, 'nami_title' => 'Kirgystan']);
		Nationality::create(['title' => 'australisch', 'nami_id' => 1420, 'nami_title' => 'australisch']);
		Nationality::create(['title' => 'GB (EU) / USA', 'nami_id' => 1421, 'nami_title' => 'GB (EU) / USA']);
		Nationality::create(['title' => 'Tschad', 'nami_id' => 1166, 'nami_title' => 'Tschad']);
		Nationality::create(['title' => 'bolivisch', 'nami_id' => 1422, 'nami_title' => 'bolivisch']);
		Nationality::create(['title' => 'Bosnien', 'nami_id' => 1167, 'nami_title' => 'Bosnien']);
		Nationality::create(['title' => 'ital./portug.', 'nami_id' => 1168, 'nami_title' => 'ital./portug.']);
		Nationality::create(['title' => 'frz', 'nami_id' => 1426, 'nami_title' => 'frz']);
		Nationality::create(['title' => 'Portugisisch', 'nami_id' => 1427, 'nami_title' => 'Portugisisch']);
		Nationality::create(['title' => 'croatisch', 'nami_id' => 1173, 'nami_title' => 'croatisch']);
		Nationality::create(['title' => 'Haiti', 'nami_id' => 1429, 'nami_title' => 'Haiti']);
		Nationality::create(['title' => 'Kroatisch', 'nami_id' => 1174, 'nami_title' => 'Kroatisch']);
		Nationality::create(['title' => 'Belgisch', 'nami_id' => 1175, 'nami_title' => 'Belgisch']);
		Nationality::create(['title' => 'russisch', 'nami_id' => 1176, 'nami_title' => 'russisch']);
		Nationality::create(['title' => 'Mexikaner', 'nami_id' => 1432, 'nami_title' => 'Mexikaner']);
		Nationality::create(['title' => 'Kongolese', 'nami_id' => 1433, 'nami_title' => 'Kongolese']);
		Nationality::create(['title' => 'irakisch', 'nami_id' => 1179, 'nami_title' => 'irakisch']);
		Nationality::create(['title' => 'mexikanisch', 'nami_id' => 1435, 'nami_title' => 'mexikanisch']);
		Nationality::create(['title' => 'Französisch', 'nami_id' => 1180, 'nami_title' => 'Französisch']);
		Nationality::create(['title' => 'brasilianische', 'nami_id' => 1436, 'nami_title' => 'brasilianische']);
		Nationality::create(['title' => 'Kanadisch / Niederländisch', 'nami_id' => 1437, 'nami_title' => 'Kanadisch / Niederländisch']);
		Nationality::create(['title' => 'rumänisch', 'nami_id' => 1182, 'nami_title' => 'rumänisch']);
		Nationality::create(['title' => 'moldawisch', 'nami_id' => 1183, 'nami_title' => 'moldawisch']);
		Nationality::create(['title' => 'US-Amerikaner', 'nami_id' => 1439, 'nami_title' => 'US-Amerikaner']);
		Nationality::create(['title' => 'Albanisch', 'nami_id' => 1184, 'nami_title' => 'Albanisch']);
		Nationality::create(['title' => 'niederländiscch', 'nami_id' => 1440, 'nami_title' => 'niederländiscch']);
		Nationality::create(['title' => 'Neiderländisch / Englisch', 'nami_id' => 1185, 'nami_title' => 'Neiderländisch / Englisch']);
		Nationality::create(['title' => 'Ägypten', 'nami_id' => 1441, 'nami_title' => 'Ägypten']);
		Nationality::create(['title' => 'jugosl.', 'nami_id' => 1186, 'nami_title' => 'jugosl.']);
		Nationality::create(['title' => 'und spanisch', 'nami_id' => 1442, 'nami_title' => 'und spanisch']);
		Nationality::create(['title' => 'bolivianisch', 'nami_id' => 1187, 'nami_title' => 'bolivianisch']);
		Nationality::create(['title' => 'Amerikanerin', 'nami_id' => 1443, 'nami_title' => 'Amerikanerin']);
		Nationality::create(['title' => '+italienisch', 'nami_id' => 1444, 'nami_title' => '+italienisch']);
		Nationality::create(['title' => 'Brasilien / Österreich', 'nami_id' => 1446, 'nami_title' => 'Brasilien / Österreich']);
		Nationality::create(['title' => 'chilenisch', 'nami_id' => 1191, 'nami_title' => 'chilenisch']);
		Nationality::create(['title' => 'Polen', 'nami_id' => 1447, 'nami_title' => 'Polen']);
		Nationality::create(['title' => 'Serbisch', 'nami_id' => 1192, 'nami_title' => 'Serbisch']);
		Nationality::create(['title' => 'kazachstan', 'nami_id' => 1193, 'nami_title' => 'kazachstan']);
		Nationality::create(['title' => 'US-amerikanisch', 'nami_id' => 1194, 'nami_title' => 'US-amerikanisch']);
		Nationality::create(['title' => 'Kongo', 'nami_id' => 1450, 'nami_title' => 'Kongo']);
		Nationality::create(['title' => 'thailändisch', 'nami_id' => 1451, 'nami_title' => 'thailändisch']);
		Nationality::create(['title' => 'Amerikanisch', 'nami_id' => 1196, 'nami_title' => 'Amerikanisch']);
		Nationality::create(['title' => 'und australisch', 'nami_id' => 1452, 'nami_title' => 'und australisch']);
		Nationality::create(['title' => 'togoisch', 'nami_id' => 1453, 'nami_title' => 'togoisch']);
		Nationality::create(['title' => 'Slowenien', 'nami_id' => 1199, 'nami_title' => 'Slowenien']);
		Nationality::create(['title' => 'Kurdisch', 'nami_id' => 1455, 'nami_title' => 'Kurdisch']);
		Nationality::create(['title' => 'Russisch', 'nami_id' => 1200, 'nami_title' => 'Russisch']);
		Nationality::create(['title' => 'Philippiner', 'nami_id' => 1456, 'nami_title' => 'Philippiner']);
		Nationality::create(['title' => 'tschetschenisch', 'nami_id' => 1457, 'nami_title' => 'tschetschenisch']);
		Nationality::create(['title' => 'Mosambik', 'nami_id' => 1458, 'nami_title' => 'Mosambik']);
		Nationality::create(['title' => 'Schweiz', 'nami_id' => 1203, 'nami_title' => 'Schweiz']);
		Nationality::create(['title' => 'Guatemala', 'nami_id' => 1459, 'nami_title' => 'Guatemala']);
		Nationality::create(['title' => 'Brasilianisch', 'nami_id' => 1460, 'nami_title' => 'Brasilianisch']);
		Nationality::create(['title' => 'Kroate', 'nami_id' => 1205, 'nami_title' => 'Kroate']);
		Nationality::create(['title' => 'Äthopien', 'nami_id' => 1461, 'nami_title' => 'Äthopien']);
		Nationality::create(['title' => 'usbekisch', 'nami_id' => 1462, 'nami_title' => 'usbekisch']);
		Nationality::create(['title' => 'Indisch', 'nami_id' => 1463, 'nami_title' => 'Indisch']);
		Nationality::create(['title' => 'USA / GB(EU)', 'nami_id' => 1465, 'nami_title' => 'USA / GB(EU)']);
		Nationality::create(['title' => 'vietnamesich', 'nami_id' => 1210, 'nami_title' => 'vietnamesich']);
		Nationality::create(['title' => 'Britsch', 'nami_id' => 1466, 'nami_title' => 'Britsch']);
		Nationality::create(['title' => 'syrisch', 'nami_id' => 1211, 'nami_title' => 'syrisch']);
		Nationality::create(['title' => 'Japanisch', 'nami_id' => 1467, 'nami_title' => 'Japanisch']);
		Nationality::create(['title' => 'Tai', 'nami_id' => 1468, 'nami_title' => 'Tai']);
		Nationality::create(['title' => 'Türkei', 'nami_id' => 1213, 'nami_title' => 'Türkei']);
		Nationality::create(['title' => 'F', 'nami_id' => 1214, 'nami_title' => 'F']);
		Nationality::create(['title' => 'Ukraine', 'nami_id' => 1215, 'nami_title' => 'Ukraine']);
		Nationality::create(['title' => 'Weißrussland', 'nami_id' => 1471, 'nami_title' => 'Weißrussland']);
		Nationality::create(['title' => 'slowenisch', 'nami_id' => 1216, 'nami_title' => 'slowenisch']);
		Nationality::create(['title' => 'Äthiopisch', 'nami_id' => 1472, 'nami_title' => 'Äthiopisch']);
		Nationality::create(['title' => 'luxemburgisch', 'nami_id' => 1218, 'nami_title' => 'luxemburgisch']);
		Nationality::create(['title' => 'Rumänien', 'nami_id' => 1219, 'nami_title' => 'Rumänien']);
		Nationality::create(['title' => '+ Spanisch', 'nami_id' => 1475, 'nami_title' => '+ Spanisch']);
		Nationality::create(['title' => 'Serbien', 'nami_id' => 1220, 'nami_title' => 'Serbien']);
		Nationality::create(['title' => 'Kenianer', 'nami_id' => 1476, 'nami_title' => 'Kenianer']);
		Nationality::create(['title' => 'Griechisch', 'nami_id' => 1221, 'nami_title' => 'Griechisch']);
		Nationality::create(['title' => 'kroatische', 'nami_id' => 1477, 'nami_title' => 'kroatische']);
		Nationality::create(['title' => 'kosovarisch', 'nami_id' => 1222, 'nami_title' => 'kosovarisch']);
		Nationality::create(['title' => 'Litauisch', 'nami_id' => 1479, 'nami_title' => 'Litauisch']);
		Nationality::create(['title' => 'kasachisch', 'nami_id' => 1225, 'nami_title' => 'kasachisch']);
		Nationality::create(['title' => 'Südkorea', 'nami_id' => 1481, 'nami_title' => 'Südkorea']);
		Nationality::create(['title' => 'tunesisch', 'nami_id' => 1482, 'nami_title' => 'tunesisch']);
		Nationality::create(['title' => 'kamerunesisch', 'nami_id' => 1229, 'nami_title' => 'kamerunesisch']);
		Nationality::create(['title' => 'philipino', 'nami_id' => 1233, 'nami_title' => 'philipino']);
		Nationality::create(['title' => 'phillipino', 'nami_id' => 1234, 'nami_title' => 'phillipino']);
		Nationality::create(['title' => 'port.', 'nami_id' => 1235, 'nami_title' => 'port.']);
		Nationality::create(['title' => 'luxemb.', 'nami_id' => 1236, 'nami_title' => 'luxemb.']);
		Nationality::create(['title' => 'N-amerikanisch', 'nami_id' => 1237, 'nami_title' => 'N-amerikanisch']);
		Nationality::create(['title' => 'F - CH', 'nami_id' => 1238, 'nami_title' => 'F - CH']);
		Nationality::create(['title' => 'NL', 'nami_id' => 1239, 'nami_title' => 'NL']);
		Nationality::create(['title' => 'theiländisch', 'nami_id' => 1243, 'nami_title' => 'theiländisch']);
		Nationality::create(['title' => 'Vietnam', 'nami_id' => 1246, 'nami_title' => 'Vietnam']);
		Nationality::create(['title' => 'Bulgarien', 'nami_id' => 1247, 'nami_title' => 'Bulgarien']);
		Nationality::create(['title' => 'bulgarisch', 'nami_id' => 1250, 'nami_title' => 'bulgarisch']);
		Nationality::create(['title' => 'norwegisch', 'nami_id' => 1251, 'nami_title' => 'norwegisch']);
		Nationality::create(['title' => 'rwander', 'nami_id' => 1252, 'nami_title' => 'rwander']);
		Nationality::create(['title' => 'ägypt.', 'nami_id' => 1254, 'nami_title' => 'ägypt.']);
		Nationality::create(['title' => 'B', 'nami_id' => 1255, 'nami_title' => 'B']);
		Nationality::create(['title' => 'dänisch', 'nami_id' => 1259, 'nami_title' => 'dänisch']);
		Nationality::create(['title' => 'türk.', 'nami_id' => 1261, 'nami_title' => 'türk.']);
		Nationality::create(['title' => 'Syrisch', 'nami_id' => 1262, 'nami_title' => 'Syrisch']);
		Nationality::create(['title' => 'domenikanisch', 'nami_id' => 1263, 'nami_title' => 'domenikanisch']);
		Nationality::create(['title' => 'tamilisch', 'nami_id' => 1265, 'nami_title' => 'tamilisch']);
		Nationality::create(['title' => 'äthiopisch', 'nami_id' => 1266, 'nami_title' => 'äthiopisch']);
		Nationality::create(['title' => 'pl', 'nami_id' => 1268, 'nami_title' => 'pl']);
		Nationality::create(['title' => 'griechisch', 'nami_id' => 1269, 'nami_title' => 'griechisch']);
		Nationality::create(['title' => 'Togolesisch', 'nami_id' => 1271, 'nami_title' => 'Togolesisch']);
		Nationality::create(['title' => 'kamerunisch', 'nami_id' => 1272, 'nami_title' => 'kamerunisch']);
		Nationality::create(['title' => 'Polnisch', 'nami_id' => 1273, 'nami_title' => 'Polnisch']);
		Nationality::create(['title' => 'persisch', 'nami_id' => 1276, 'nami_title' => 'persisch']);
		Nationality::create(['title' => 'Irak', 'nami_id' => 1277, 'nami_title' => 'Irak']);
		Nationality::create(['title' => 'Ukrainisch', 'nami_id' => 1278, 'nami_title' => 'Ukrainisch']);
		Nationality::create(['title' => 'Tschechisch', 'nami_id' => 1279, 'nami_title' => 'Tschechisch']);
    }
}
